[config]
version_check = false
fallback_color = "#ffbf9b"

prefer = "darkness"

[templates.waybar]
input_path = '~/.config/matugen/waybar/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.hyprland]
input_path = '~/.config/matugen/hyprland/colors.lua'
output_path = '~/.config/hypr/constants/colors.lua'

[templates.hyprlock]
input_path = '~/.config/matugen/hyprlock/hyprlock.conf'
output_path = '~/.config/hypr/hyprlock.conf'

[templates.swaync]
input_path = '~/.config/matugen/swaync/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = "swaync-client -rs"

[templates.wofi]
input_path = '~/.config/matugen/wofi/style.css'
output_path = '~/.config/wofi/style.css'
