[config]
version_check = false
fallback_color = "#ffbf9b"

# Cache location $XDG_CACHE_HOME/matugen/<file> or $HOME/.cache/matugen/images/<file>
caching = true

# choices: [darkness, lightness, saturation, less-saturation, value, closest-to-fallback]
prefer = "darkness"



[templates.waybar]
input_path = '~/.config/matugen/waybar/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.hyprland]
input_path = '~/.config/matugen/hyprland/colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.hyprlock]
input_path = '~/.config/matugen/hyprlock/hyprlock.conf'
output_path = '~/.config/hypr/hyprlock.conf'

[templates.swaync]
input_path = '~/.config/matugen/swaync/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = "swaync-client -rs"

[templates.wofi]
input_path = '~/.config/matugen/wofi/style.css'
output_path = '~/.config/wofi/style.css'
