###################
### Configs ###
###################

$SCRIPT_PATH= $HOME/.config/hypr/script
$launcher = /usr/bin/app2unit

$config_prefix = ~/.config/hypr/conf

source = $config_prefix/inputs.conf
source = $config_prefix/monitors.conf
source = $config_prefix/programs.conf
source = $config_prefix/windowRules.conf
source = $config_prefix/workspaceRules.conf
source = $config_prefix/binds.conf
source = $config_prefix/gestures.conf
source = $config_prefix/layouts.conf

source = $config_prefix/animations.conf
source = $config_prefix/decorations.conf

#################
### AUTOSTART ###
#################

exec-once = kbuildsycoca6

exec-once = $launcher $terminal
exec-once = $launcher awww-daemon
#exec-once = sleep 2 && $SCRIPT_PATH/wallpaperSwitcher.sh set-random

# Screen Sharing
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP


#####################
### LOOK AND FEEL ###
#####################

# Colors
source = ~/.config/hypr/colors.conf

general {
    border_size = 2 

    gaps_in = 1
    gaps_out = 5

    col.active_border = $outline
#    col.inactive_border = rgba(595959aa)
    col.inactive_border = rgba(595959aa)

    resize_on_border = true
    allow_tearing = false

    layout = scrolling

    snap {
        enabled = true
        window_gap = 15
        monitor_gap = 15
        border_overlap = false
        respect_gaps = false
    }
}


misc {
    force_default_wallpaper = 0 
    disable_hyprland_logo = true 
    disable_splash_rendering = true
    focus_on_activate = true
    middle_click_paste = false
}


ecosystem {
    no_donation_nag = true
}

debug {
    overlay = false
}

xwayland {
    enabled = true
    force_zero_scaling = true
}
###################
### PERMISSIONS ###
###################

ecosystem {
   enforce_permissions = 1
}

permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(bin|local/bin)/hyprlock, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
