gesture = 4, up, cursorZoom, 1.8
gesture = 4, down, cursorZoom, 1.8

gesture = 3, up, fullscreen
gesture = 3, down, fullscreen

#bind = $mainMod, H, movefocus, l
#bind = $mainMod, L, movefocus, r
gesture = 3, left, dispatcher, movefocus, r
gesture = 3, right, dispatcher, movefocus, l

