# No Gap when One window in non special workspace
#workspace = w[tv1]s[false], gapsout:0, gapsin:0
#workspace = f[1]s[false], gapsout:0, gapsin:0

# Monitors
#workspace = 1, default:true, persistent:true, monitor:eDP-1
#workspace = 2, persistent:true, monitor:eDP-1
#workspace = 3, persistent:true, monitor:eDP-1
#workspace = 4, persistent:true, monitor:eDP-1
#workspace = 5, persistent:true, desc:Acer Technologies XV270U X1 2511033253LEH
#workspace = 6, persistent:true, desc:Acer Technologies XV270U X1 2511033253LEH
#workspace = 7, persistent:true, desc:Acer Technologies XV270U X1 2511033253LEH
#workspace = 8, persistent:true, desc:Acer Technologies XV270U X1 2511033253LEH

#workspace = 8, persistent:true, desc:AU Optronics 0xD291
#workspace = 7, persistent:true, desc:AU Optronics 0xD291
#workspace = 6, persistent:true, desc:AU Optronics 0xD291
#workspace = 5, persistent:true, desc:AU Optronics 0xD291
workspace = 4, persistent:true,# desc:Acer Technologies XV270U X1 2511033253LEH
workspace = 3, persistent:true,# desc:Acer Technologies XV270U X1 2511033253LEH
workspace = 2, persistent:true,# desc:Acer Technologies XV270U X1 2511033253LEH
workspace = 1, default:true,persistent:true, persistent:true,# desc:Acer Technologies XV270U X1 2511033253LEH

# Dwindle layout for special workspace
workspace = s[true], layout:dwindle
