
[mgr]
show_hidden = true
linemode = "size"


[opener]
pdf = [
    { run = 'zathura "$0"', block = true }
]
edit = [
    { run = 'nvim "$0"', block = true }
]
open_default = [
	{ run = 'xdg-open "$0"' }
]


[open]
rules = [
    { name = "*.pdf", use = "pdf" },

    { mime = "text/*", use = "edit" },

    { name = "*", use = "open_default" }
]


[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
